# Generated by Django 4.2 on 2023-05-08 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField(default=None)),
            ],
        ),
    ]
