# Generated by Django 4.2 on 2023-06-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingsession',
            old_name='created_At',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='shopping_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_session', to='shopping.shoppingsession'),
        ),
    ]
