# Generated by Django 4.2 on 2023-06-14 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping', '0001_initial'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingsession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shopping_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_session', to='shopping.shoppingsession'),
        ),
    ]
