# Generated by Django 4.2 on 2023-06-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingsession',
            old_name='subtotal',
            new_name='total',
        ),
    ]
