# Generated by Django 4.2 on 2023-06-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_rename_created_at_shoppingsession_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingsession',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
