# Generated by Django 4.2 on 2023-05-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_profile',
            new_name='user',
        ),
    ]
